name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/**.md'
      - '.github/**'

jobs:
  publish:
    name: Publish the app
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Publish
      shell: pwsh
      run: |
        Set-Location "$env:GITHUB_WORKSPACE"
        dotnet restore
        dotnet publish -c Release -r linux-x64 -p:PublishDir="$env:GITHUB_WORKSPACE\Release\linux-x64"
        dotnet publish -c Release -r win-x64 -p:PublishDir="$env:GITHUB_WORKSPACE\Release\win-x64"
        dotnet publish -c Release -r osx-x64 -p:PublishDir="$env:GITHUB_WORKSPACE\Release\osx-x64"
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\Release\win-x64\" -DestinationPath "CW-win-x64.zip"
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\Release\linux-x64\" -DestinationPath "CW-linux-x64.zip"
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\Release\osx-x64\" -DestinationPath "CW-osx-x64.zip"
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: ./*.zip
